#ifndef LANDING_PAGE_GENERATOR_H
#define LANDING_PAGE_GENERATOR_H

#include <string>
#include <cstring>

/**
 * Testable landing page HTML generation logic that mirrors sendLandingPageResponse()
 * from web_server.cpp.
 *
 * In web_server.cpp, the landing page is generated by writing HTML fragments to a
 * WiFiClient. This function produces the same HTML as a std::string for property testing.
 *
 * Parameters:
 *   status   - The health status string to display
 *   version  - The health version string to display
 *   isCached - Whether the data is from cache (shows warning message)
 *   hasFailed - Whether the latest health check failed
 *
 * Behavior (mirrors web_server.cpp):
 *   - When hasFailed is true AND status is empty: show error-only message
 *   - Otherwise: show status table (with warning if hasFailed is true)
 */
inline std::string generateLandingPageHtml(const char* status, const char* version,
                                           bool isCached, bool hasFailed) {
    std::string html;

    html += "HTTP/1.1 200 OK\r\n";
    html += "Content-Type: text/html\r\n";
    html += "Connection: close\r\n";
    html += "\r\n";
    html += "<!DOCTYPE html>\r\n";
    html += "<html lang=\"en\">\r\n";
    html += "<head>\r\n";
    html += "<meta charset=\"UTF-8\">\r\n";
    html += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n";
    html += "<title>TempMon Health</title>\r\n";
    html += "<style>\r\n";
    html += "body { font-family: sans-serif; margin: 2em; background: #f9f9f9; color: #222; }\r\n";
    html += "h1 { color: #333; }\r\n";
    html += ".status-table { border-collapse: collapse; margin-top: 1em; }\r\n";
    html += ".status-table th, .status-table td { border: 1px solid #ccc; padding: 0.5em 1em; text-align: left; }\r\n";
    html += ".status-table th { background: #eee; }\r\n";
    html += ".error { color: #c00; background: #fee; border: 1px solid #c00; padding: 0.75em; margin-top: 1em; border-radius: 4px; }\r\n";
    html += ".warning { color: #856404; background: #fff3cd; border: 1px solid #ffc107; padding: 0.75em; margin-top: 1em; border-radius: 4px; }\r\n";
    html += "</style>\r\n";
    html += "</head>\r\n";
    html += "<body>\r\n";
    html += "<h1>TempMon Health</h1>\r\n";

    if (hasFailed && status[0] == '\0') {
        // Health check failed and no cached data available
        html += "<div class=\"error\" role=\"alert\">\r\n";
        html += "<p>Health check failed. No cached data available.</p>\r\n";
        html += "</div>\r\n";
    } else {
        if (hasFailed) {
            // Health check failed but cached data exists
            html += "<div class=\"warning\" role=\"alert\">\r\n";
            html += "<p>Latest health check failed. Showing cached data.</p>\r\n";
            html += "</div>\r\n";
        }
        // Display health status and version
        html += "<table class=\"status-table\" aria-label=\"Health status\">\r\n";
        html += "<tr><th scope=\"row\">Status</th><td>";
        html += status;
        html += "</td></tr>\r\n";
        html += "<tr><th scope=\"row\">Version</th><td>";
        html += version;
        html += "</td></tr>\r\n";
        html += "</table>\r\n";
    }

    html += "</body>\r\n";
    html += "</html>\r\n";

    return html;
}

#endif
